name: Truffle CI

on:
  push:
    branches:
    # long-lived branches
    - master
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.X
      uses: actions/setup-node@v1
      with:
        node-version: '10'
    - run: npm install
    - run: npm test